services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: muoffice-sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MUOffice@2026
      - MSSQL_PID=Developer
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
