services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=WebProgProjc
    volumes:
      - postgres-db-data:/var/lib/postgresql

volumes:
  postgres-db-data:
