version: "3.4"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Your_password123
      - POSTGRES_DB=WebProgProjc
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
  postgres-db-data:
